# Chapter 7 - Data Cleaning and Preparation

## 7.1 Handling Missing Data

In [5]:
import pandas as pd
import numpy as np

In [6]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [7]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [8]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [9]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [10]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [12]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [13]:
float_data = pd.Series([1,2,None], dtype='float64')

In [14]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [15]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [16]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [18]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [19]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [21]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [22]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [24]:
data[4] = np.nan

In [25]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [26]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [54]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [55]:
df.iloc[:4, 1] = np.nan

In [56]:
df.iloc[:2, 2] = np.nan

In [57]:
df

0         1         2
0 -1.429355       NaN       NaN
1  0.504092       NaN       NaN
2  0.230181       NaN -0.735074
3  0.125764       NaN  0.303202
4 -0.159793 -0.319491 -0.106808
5  0.981965 -2.217138  1.266485
6  1.342527  0.936903  1.893250

In [58]:
df.dropna()

0         1         2
4 -0.159793 -0.319491 -0.106808
5  0.981965 -2.217138  1.266485
6  1.342527  0.936903  1.893250

In [59]:
df.dropna(thresh=2)

0         1         2
2  0.230181       NaN -0.735074
3  0.125764       NaN  0.303202
4 -0.159793 -0.319491 -0.106808
5  0.981965 -2.217138  1.266485
6  1.342527  0.936903  1.893250

### Filling in Missing Data 

In [60]:
df.fillna(0)

0         1         2
0 -1.429355  0.000000  0.000000
1  0.504092  0.000000  0.000000
2  0.230181  0.000000 -0.735074
3  0.125764  0.000000  0.303202
4 -0.159793 -0.319491 -0.106808
5  0.981965 -2.217138  1.266485
6  1.342527  0.936903  1.893250

In [61]:
df.fillna({1: 0.5, 2:0})

0         1         2
0 -1.429355  0.500000  0.000000
1  0.504092  0.500000  0.000000
2  0.230181  0.500000 -0.735074
3  0.125764  0.500000  0.303202
4 -0.159793 -0.319491 -0.106808
5  0.981965 -2.217138  1.266485
6  1.342527  0.936903  1.893250

In [63]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [64]:
df.iloc[2:, 1] = np.nan

In [65]:
df.iloc[4:, 2] = np.nan

In [66]:
df

0         1         2
0 -0.978231 -0.814446  0.152642
1  0.187687  0.185405 -0.966430
2 -0.642443       NaN  0.550910
3 -1.984250       NaN  0.039050
4 -0.453970       NaN       NaN
5 -0.772555       NaN       NaN

In [67]:
df.fillna(method="ffill")

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0 -0.978231 -0.814446  0.152642
1  0.187687  0.185405 -0.966430
2 -0.642443  0.185405  0.550910
3 -1.984250  0.185405  0.039050
4 -0.453970  0.185405  0.039050
5 -0.772555  0.185405  0.039050

In [68]:
df.fillna(method="ffill", limit=2)

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0 -0.978231 -0.814446  0.152642
1  0.187687  0.185405 -0.966430
2 -0.642443  0.185405  0.550910
3 -1.984250  0.185405  0.039050
4 -0.453970       NaN  0.039050
5 -0.772555       NaN  0.039050

In [69]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [70]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Data Transformation

### Removing Duplicates

In [71]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
             "k2": [1, 1, 2, 3, 3, 4, 4]})

In [72]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [73]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [74]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [75]:
data["v1"] = range(7)

In [76]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [78]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [79]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [81]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
    "pastrami", "corned beef", "bacon",
    "pastrami", "honey ham", "nova lox"],
    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [82]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [83]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [84]:
data["animal"] = data["food"].map(meat_to_animal)

In [85]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [86]:
def get_animal(x):
    return meat_to_animal[x]

In [87]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [88]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [89]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [90]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [91]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [92]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [95]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [102]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
    index=["Ohio", "Colorado", "New York"],
    columns=["one", "two", "three", "four"])

In [109]:
data.index.map()

TypeError: Index.map() missing 1 required positional argument: 'mapper'

In [110]:
data.index = data.index.map(transform)

NameError: name 'transform' is not defined

In [111]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [108]:
data.rename(index={"OHIO": "INDIANA"},
    columns={"three": "peekaboo"})

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

### Discretization and Binning

In [116]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [117]:
bins = [18, 25, 35, 60, 100]

In [118]:
age_categories = pd.cut(ages, bins)

In [119]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [120]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [121]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [122]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [123]:
pd.value_counts(age_categories)

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [125]:
pd.Series(age_categories).value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [126]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [127]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [128]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [129]:
data = np.random.uniform(size=20)

In [130]:
pd.cut(data, 4, precision=2)

[(0.27, 0.51], (0.51, 0.76], (0.51, 0.76], (0.76, 1.0], (0.27, 0.51], ..., (0.76, 1.0], (0.27, 0.51], (0.028, 0.27], (0.76, 1.0], (0.028, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.028, 0.27] < (0.27, 0.51] < (0.51, 0.76] < (0.76, 1.0]]

In [131]:
data = np.random.standard_normal(1000)

In [132]:
quartiles = pd.qcut(data, 4, precision=2)

In [133]:
quartiles

[(0.72, 3.85], (-0.67, 0.034], (-2.9899999999999998, -0.67], (0.034, 0.72], (0.72, 3.85], ..., (-2.9899999999999998, -0.67], (-2.9899999999999998, -0.67], (-2.9899999999999998, -0.67], (-0.67, 0.034], (-2.9899999999999998, -0.67]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9899999999999998, -0.67] < (-0.67, 0.034] < (0.034, 0.72] < (0.72, 3.85]]

In [134]:
pd.value_counts(quartiles)

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.9899999999999998, -0.67]    250
(-0.67, 0.034]                  250
(0.034, 0.72]                   250
(0.72, 3.85]                    250
Name: count, dtype: int64

In [135]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.981, -1.29]    100
(-1.29, 0.0338]    400
(0.0338, 1.288]    400
(1.288, 3.853]     100
Name: count, dtype: int64

### Detecting and Filtering Outliers

In [136]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [137]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000960    -0.056438    -0.012140    -0.006363
std       1.000878     1.010372     1.036596     0.978424
min      -3.239895    -3.134376    -3.466666    -2.951517
25%      -0.712306    -0.794726    -0.695894    -0.649445
50%      -0.005803    -0.060010    -0.000085    -0.029604
75%       0.673913     0.637560     0.659197     0.656659
max       2.865620     2.907648     3.226703     3.040829

In [138]:
col = data[2]

In [139]:
col[col.abs() > 3]

484    3.226703
509   -3.466666
Name: 2, dtype: float64

In [140]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
118 -3.217465  0.395972 -0.157909  1.409790
183 -0.068542  0.620102  0.237216  3.040829
317 -3.052812 -0.122041 -1.226470  0.231729
484 -0.783058 -0.472540  3.226703 -0.163574
509 -2.109443 -1.877866 -3.466666 -0.067218
608 -0.710655 -3.134376  0.802480 -0.443775
730 -3.239895 -0.497782  0.792655 -2.329928
842 -3.086429 -0.460053 -0.745563  0.664408

In [141]:
data[data.abs() > 3] = np.sign(data) * 3

In [142]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.000363    -0.056303    -0.011900    -0.006404
std       0.999029     1.009971     1.034458     0.978298
min      -3.000000    -3.000000    -3.000000    -2.951517
25%      -0.712306    -0.794726    -0.695894    -0.649445
50%      -0.005803    -0.060010    -0.000085    -0.029604
75%       0.673913     0.637560     0.659197     0.656659
max       2.865620     2.907648     3.000000     3.000000

In [143]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0 -1.0  1.0
3  1.0 -1.0 -1.0  1.0
4  1.0  1.0 -1.0 -1.0

### Permutation and Random Sampling

In [146]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5,7)))

In [147]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [148]:
sampler = np.random.permutation(5)

In [149]:
sampler

array([2, 3, 1, 0, 4])

In [150]:
df.take(sampler)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [153]:
df.iloc[sampler]

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [154]:
column_sampler = np.random.permutation(7)

In [155]:
column_sampler

array([2, 5, 4, 6, 3, 1, 0])

In [156]:
df.take(column_sampler, axis="columns")

2   5   4   6   3   1   0
0   2   5   4   6   3   1   0
1   9  12  11  13  10   8   7
2  16  19  18  20  17  15  14
3  23  26  25  27  24  22  21
4  30  33  32  34  31  29  28

In [157]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20

In [159]:
choices = pd.Series([5,6,-1,6,4])

In [160]:
choices.sample(n=10, replace=True)

2   -1
4    4
4    4
2   -1
3    6
2   -1
0    5
1    6
4    4
1    6
dtype: int64

### Computing Indicator/Dummy Variables

In [162]:
 df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": range(6)})

In [163]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [164]:
pd.get_dummies(df["key"], dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [165]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)

In [167]:
df_with_dummy = df[["data1"]].join(dummies)

In [168]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [169]:
mnames = ["movie_id", "title", "genres"]

In [ ]:
# Won't work as we don't have the data set 
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
header=None, names=mnames, engine="python")

In [172]:
np.random.seed(12345)

In [175]:
values = np.random.uniform(size=10)

In [176]:
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [177]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [178]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False        True       False
1       False       False       False       False        True
2        True       False       False       False       False
3        True       False       False       False       False
4       False        True       False       False       False
5       False       False       False        True       False
6       False       False       False       False        True
7       False       False       False       False        True
8       False       False       False       False        True
9       False       False       False        True       False

## 7.3 Extension Data Types

In [179]:
s = pd.Series([1,2,3,None])

In [180]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [181]:
s.dtype

dtype('float64')

In [182]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [183]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [184]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [185]:
s.dtype

Int64Dtype()

In [186]:
s[3]

<NA>

In [187]:
s[3] is pd.NA

True

In [188]:
s = pd.Series([1,2,3,None], dtype="Int64")

In [189]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [190]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [191]:
 df = pd.DataFrame({"A": [1, 2, None, 4],
   "B": ["one", "two", "three", None],
   "C": [False, None, False, True]})

In [192]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [193]:
df["A"] = df["A"].astype("Int64")

In [194]:
df["B"] = df["B"].astype("string")

In [195]:
df["C"] = df["C"].astype("boolean")

In [196]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 String Manipulation

### Python Built-In String Object Methods

In [197]:
val = "a,b, guido"

In [198]:
val.split(",")

['a', 'b', ' guido']

In [199]:
pieces = [x.strip() for x in val.split(",")]

In [200]:
pieces

['a', 'b', 'guido']

In [201]:
first, second, third = pieces

In [202]:
first+"::"+second+"::"+third

'a::b::guido'

In [203]:
"::".join(pieces)

'a::b::guido'

In [204]:
"guido" in val

True

In [205]:
val.index(",")

1

In [206]:
val.find(":")

-1

In [207]:
val.index(":")

ValueError: substring not found

In [208]:
val.count(",")

2

In [209]:
val.replace("," , "::")

'a::b:: guido'

In [211]:
val.replace("," , "")

'ab guido'

### Regular expressions 

In [212]:
import re

In [213]:
text = "foo    bar\t baz  \tqux"

In [215]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [219]:
regex = re.compile(r"\s+")

In [221]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [222]:
regex.findall(text)

['    ', '\t ', '  \t']

In [223]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [224]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [225]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [226]:
m = regex.search(text)

In [227]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [229]:
text[m.start():m.end()]

'dave@google.com'

In [230]:
print(regex.match(text))

None


In [232]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [233]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [234]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [235]:
m = regex.match("wesm@bright.net")

In [236]:
m.groups()

('wesm', 'bright', 'net')

In [237]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [239]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


### String Functions in pandas

In [241]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}

In [242]:
data = pd.Series(data)

In [243]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [244]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [245]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [246]:
data_as_string_ext = data.astype('string')

In [247]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [248]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [249]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [251]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [252]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [253]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [254]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [255]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [256]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## 7.5 Categorical Data

In [257]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [258]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [259]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [260]:
pd.value_counts(values)

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [261]:
values = pd.Series([0,1,0,0] * 2)

In [262]:
dim = pd.Series(['apple', 'orange'])

In [263]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [264]:
dim

0     apple
1    orange
dtype: object

In [265]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Categorical Extension Type in pandas

In [266]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [267]:
N = len(fruits)

In [268]:
rng = np.random.default_rng(seed=12345)

In [270]:
df = pd.DataFrame({'fruit': fruits,
   'basket_id': np.arange(N),
   'count': rng.integers(3, 15, size=N),
   'weight': rng.uniform(0, 4, size=N)},
   columns=['basket_id', 'fruit', 'count', 'weight'])

In [271]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [272]:
fruit_cat = df['fruit'].astype('category')

In [273]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [274]:
c = fruit_cat.array

In [275]:
type(c)

pandas.core.arrays.categorical.Categorical

In [276]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [277]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [278]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [282]:
df['fruit'] = df['fruit'].astype('category')

In [283]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [284]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [285]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [286]:
categories = ['foo', 'bar', 'baz']

In [287]:
codes = [0, 1, 2, 0, 0, 1]

In [289]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [290]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [292]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [293]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [294]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### Computations with Categoricals

In [295]:
rng = np.random.default_rng(seed=12345)

In [296]:
draws = rng.standard_normal(1000)

In [297]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [298]:
bins = pd.qcut(draws,4)

In [299]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [300]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [301]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [302]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [305]:
bins = pd.Series(bins, name='quartile') 

In [306]:
results = (pd.Series(draws)
   .groupby(bins)
   .agg(['count', 'min', 'max'])
   .reset_index())

/var/folders/s2/3b5ld8z148l3qsrn3gkrglv00000gp/T/ipykernel_1918/898208881.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


In [307]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [308]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

### Better performance with categoricals

In [309]:
n = 10_000_000

In [310]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [311]:
categories = labels.astype('category')

In [312]:
labels.memory_usage(deep=True)

548

In [313]:
categories.memory_usage(deep=True)

520

In [314]:
%time _ = labels.astype('category')

CPU times: user 683 µs, sys: 52 µs, total: 735 µs
Wall time: 708 µs


In [315]:
%timeit labels.value_counts()

38.4 µs ± 272 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [317]:
%timeit categories.value_counts()

58.9 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Categorical Methods

In [318]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [319]:
cat_s = s.astype('category')

In [320]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [321]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [322]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [323]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [324]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [325]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [326]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [327]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [328]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [329]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [330]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

### Creating dummy variables for modeling

In [332]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [334]:
pd.get_dummies(cat_s, dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0